package constants

const (
	PROVIDER_ETHERSCAN  = "etherscan"
	PROVIDER_BLOCKSCOUT = "blockscout"

	EXTERNAL_REPORT = "EXTERNAL_REPORT"
	INTERNAL_REPORT = "INTERNAL_REPORT"
	ERC20_REPORT    = "ERC20_REPORT"
	ERC721_REPORT   = "ERC721_REPORT"

	EXTERNAL_REPORT_ACTION = "txlist"
	INTERNAL_REPORT_ACTION = "txlistinternal"
	ERC20_REPORT_ACTION    = "tokentx"
	ERC721_REPORT_ACTION   = "tokennfttx"

	TRANSACTION_TYPE_ETH_TRANSFER      = "ETH Transfer"
	TRANSACTION_TYPE_INTERNAL_TRANSFER = "Internal"
	TRANSACTION_TYPE_ERC20_TRANSFER    = "ERC-20 Transfer"
	TRANSACTION_TYPE_ERC721_TRANSFER   = "ERC-721 Transfer"

	TOKEN_SYMBOL_ETH = "ETH"

	DATE_FORMAT_YYYY_MM_DD_HH_MM_SS = "2006-01-02 15:04:05"
)
